wandb_version: 1

batch_size:
  desc: null
  value: 32
epochs:
  desc: null
  value: 2
lr:
  desc: null
  value: 0.001
model:
  desc: null
  value: resnet34
_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.14.2
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1681426455.079342
    t:
      1:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      2:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      3:
      - 2
      - 23
      - 37
      4: 3.10.11
      5: 0.14.2
      8:
      - 1
      - 3
      - 5
